import { Dai_Banna_SIL, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lindsay's sweet treat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >

        <div className="size-full max-h-screen grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen font-[family-name:var(--font-geist-sans)] pt-20 sm:pt-20">
          <Header className="pl-0 w-full" />
          <div className="pb-20 gap-16 sm:pl-0 sm:pr-0 md:p-20">
            {children}
          </div>
          <Footer />
          

        </div>
      </body>
    </html>
  );
}
